version: '3.8'

services:
  gerstead_service:
    image: andrewgersh/gerstead:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "app.py"]
      interval: 30s
      retries: 3

networks:
  app-network:
    driver: overlay

